name: CI
on: [push, pull_request]
env:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"

defaults:
  run:
    shell: bash

jobs:
  validate-gradle-wrapper:
    name: "Validate Gradle wrapper"
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.4.2

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-2022
          - macos-11

    name: "Test (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 11.0.14+101 # We must use Java 15 or earlier until https://youtrack.jetbrains.com/issue/KT-47039 is fixed.
          distribution: adopt

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v4.2.4
        with:
          path: ~/.gradle/wrapper/dists
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/*') }}

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v4.2.4
        with:
          path: ~/.gradle/caches
          key: gradle-packages-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', 'gradle/wrapper/*') }}
          restore-keys: gradle-packages-${{ runner.os }}

      - name: Allow modifying macOS certificate trust settings without prompting
        if: startsWith(matrix.os, 'macos')
        run: sudo security authorizationdb write com.apple.trust-settings.user allow

      - name: Build and test
        run: ./gradlew --parallel check

      - name: Clean up dependencies before caching
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: |
          rm -rf ~/.gradle/caches/gradle-cache/caches/modules-2/modules-2.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/plugin-resolution/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/scripts/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/scripts-remapped/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/fileHashes/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/fileContent/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/javaCompile/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/executionHistory/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/generated-gradle-jars/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/jars-*/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/transforms-1/transforms-1.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/journal-1/file-access.bin
          rm -rf ~/.gradle/caches/gradle-cache/caches/journal-1/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/daemon/*/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/daemon/*/*.log
          rm -rf ~/.gradle/caches/gradle-cache/kotlin-profile/*

  publish:
    name: "Publish"
    runs-on: ubuntu-24.04

    needs:
      - test
      - validate-gradle-wrapper

    permissions:
      contents: write # Required to be able to publish releases, see https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
      issues: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 11 # We must use Java 15 or earlier until https://youtrack.jetbrains.com/issue/KT-47039 is fixed.
          distribution: adopt

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v4.2.4
        with:
          path: ~/.gradle/wrapper/dists
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/*') }}

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v4.2.4
        with:
          path: ~/.gradle/caches
          key: gradle-packages-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', 'gradle/wrapper/*') }}
          restore-keys: gradle-packages-${{ runner.os }}

      - name: Install release tooling
        run: npm --prefix=.github/workflows/release clean-install

      - name: Create release
        run: npx --prefix=.github/workflows/release semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository == 'charleskorn/okhttp-system-keystore' && github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Build
        run: ./gradlew assemble

      - name: Get tag
        id: get_tag
        run: |
          echo "Local changes, if any:"
          git status

          if git describe --tags --abbrev=0 --exact-match >/dev/null; then
            tag=$(git describe --tags --abbrev=0 --exact-match)
            echo "Found tag $tag."
            echo "tag=$tag" >> $GITHUB_OUTPUT
          else
            echo "git describe failed, skipping release:"
            git describe --tags --abbrev=0 --exact-match || true
            echo "skip=true" >> $GITHUB_OUTPUT
          fi
        if: github.repository == 'charleskorn/okhttp-system-keystore' && github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Assemble release
        run: ./gradlew assembleRelease
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASSPHRASE }}
        if: github.repository == 'charleskorn/okhttp-system-keystore' && github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.get_tag.outputs.skip != 'true'

      - name: Publish release
        run: ./gradlew publishRelease
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASSPHRASE }}
        if: github.repository == 'charleskorn/okhttp-system-keystore' && github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.get_tag.outputs.skip != 'true'

      - name: Add artifacts to GitHub release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: build/release/*
          fail_on_unmatched_files: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository == 'charleskorn/okhttp-system-keystore' && github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.get_tag.outputs.skip != 'true'
