name: CI
on: [push, pull_request]
env:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"

defaults:
  run:
    shell: bash

jobs:
  validate-gradle-wrapper:
    name: "Validate Gradle wrapper"
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

  test-and-publish:
    name: "Test and publish"
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: adopt

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/wrapper/dists
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/*') }}

      - name: Cache packages
        id: cache-packages
        uses: actions/cache@v2.1.7
        with:
          path: ~/.gradle/caches
          key: gradle-packages-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', 'gradle/wrapper/*') }}
          restore-keys: gradle-packages-${{ runner.os }}

      - name: Build and test
        run: ./gradlew --parallel check

      - name: Clean up dependencies before caching
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: |
          rm -rf ~/.gradle/caches/gradle-cache/caches/modules-2/modules-2.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/plugin-resolution/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/scripts/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/scripts-remapped/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/fileHashes/
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/fileContent/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/javaCompile/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/executionHistory/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/*/generated-gradle-jars/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/jars-*/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/transforms-1/transforms-1.lock
          rm -rf ~/.gradle/caches/gradle-cache/caches/journal-1/file-access.bin
          rm -rf ~/.gradle/caches/gradle-cache/caches/journal-1/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/daemon/*/*.lock
          rm -rf ~/.gradle/caches/gradle-cache/daemon/*/*.log
          rm -rf ~/.gradle/caches/gradle-cache/kotlin-profile/*
